### ISSUE TITLE
QST: pytask-parallel with sphinx

### ISSUE THREAD

**Issue by hildebrandecon** [pytask-dev/pytask-parallel#35]
Good morning Tobi,

I thought about using pytask-parallel for a project where I also use sphinx to compile a documentation of my code. There seems to be an issue with that, however. Say, I have the `.rst` documentation files in the folder `src/00_documentation`. The task in that folder is the following:

```python 
"""
Build the pdf and html documentation using Sphinx.

`task_build_documentation` executes Sphinx via pytask-latex and stores the output in
*bld/00_documentation*.
"""
import subprocess
from pathlib import Path

import pytask

from src.config import BLD
from src.config import SRC


@pytask.mark.depends_on(
    list(Path(__file__).resolve().parent.glob("*.rst"))
    + [SRC / "00_documentation" / "conf.py"]
)
@pytask.mark.parametrize(
    "builder, produces",
    [
        ("latexpdf", BLD / "00_documentation" / "latex" / "project_documentation.pdf"),
        ("html", (BLD / "00_documentation" / "html").rglob("*.*")),
    ],
)
def task_build_documentation(builder, produces):
    subprocess.run(
        [
            "sphinx-build",
            "-M",
            builder,
            SRC.joinpath("00_documentation").as_posix(),
            BLD.joinpath("00_documentation").as_posix(),
        ]
    )

```

Now, I am running:
```python
pytask -n auto src/00_documentation/
```

I get the following error:

![image](https://user-images.githubusercontent.com/61334700/153152202-e2ffe223-cc8b-4ca9-b0ab-9a0168d1a42f.png)
![image](https://user-images.githubusercontent.com/61334700/153152392-9b57de25-c6f1-47d1-94cc-c9fd4aa5a106.png)
![image](https://user-images.githubusercontent.com/61334700/153152583-d8b76a2b-4302-4ac1-bd7a-f1727975dacb.png)

If you need further details for reproducing the error, I can share an example project with you! I hope this helps to improve the tool even further.

Best,
Sebastian

**Comment by tobiasraabe** [comment]
The only generator I can see is `(BLD / "00_documentation" / "html").rglob("*.*")`. Try `list((BLD / "00_documentation" / "html").rglob("*.*"))`

**Comment by hildebrandecon** [comment]
Great, that works! Thanks a lot. However, even better is `BLD / "00_documentation" / "html" / "00_index.html"` as it fixes the issue of running in parallel as well as the issue of pytask not recognising whether the html output was created at all. This will be fixed in future version of the templates of HMG.
